# Generated by Django 3.0.5 on 2021-07-19 12:01

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=15)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.Category')),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='code')),
                ('brand', models.CharField(blank=True, default='', max_length=250)),
                ('code', models.CharField(blank=True, db_index=True, max_length=10)),
                ('title', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, db_index=True, default='', max_length=1000, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('photo', models.ImageField(blank=True, upload_to='media/items/%Y/%m/%d', verbose_name='Фото')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В продаже')),
                ('on_delete', models.BooleanField(default=False, verbose_name='Пометка на удаление')),
                ('quantity_unit', models.CharField(choices=[('GRM', 'грамм'), ('KGM', 'килограмм'), ('LTR', 'литр'), ('MMT', 'миллиметр'), ('MTK', 'квадратный метр'), ('MTQ', 'кубический метр'), ('MTR', 'метр'), ('MGM', 'миллиграмм'), ('MLT', 'миллилитр'), ('MMQ', 'миллиметр кубический'), ('PCE', 'штук'), ('DMQ', 'дециметр кубический'), ('CMT', 'сантиметр'), ('NMP', 'упаковка'), ('NBB', 'бобина(бухта)')], default='шт', max_length=3)),
                ('quantity_min', models.IntegerField(verbose_name='Минимальное количество заказ')),
                ('analogs', models.ManyToManyField(related_name='analog', to='shop.Item', verbose_name='Аналоги')),
                ('category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='shop.Category')),
                ('related', models.ManyToManyField(related_name='related_item', to='shop.Item', verbose_name='Сопутствующие товары')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('title', 'price'),
            },
        ),
        migrations.CreateModel(
            name='SpecItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код характеристики')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование арактеристики, (и единица измерения)')),
                ('uom', models.CharField(max_length=20, null=True, verbose_name='Еденицы измерения')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики товара',
            },
        ),
        migrations.CreateModel(
            name='SpecValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Значение характеристики')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_value', to='shop.Item')),
                ('spec_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value', to='shop.SpecItem')),
            ],
            options={
                'verbose_name': 'Значение характеристики',
                'verbose_name_plural': 'Значения характеристик',
            },
        ),
        migrations.CreateModel(
            name='ItemRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('rating', models.CharField(choices=[('5', 5), ('4', 4), ('3', 3), ('2', 2), ('1', 1)], default='5', max_length=1, verbose_name='Мнение пользователя о товаре')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_rating', to='shop.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отценка пользователя',
                'verbose_name_plural': 'Отценки пользователей',
                'ordering': ('item', 'rating'),
                'unique_together': {('item', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='shop.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Предмет помещенный в избранное',
                'verbose_name_plural': 'Избранное',
                'ordering': ('item', 'create_date'),
                'unique_together': {('user', 'item')},
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ('expire_date', 'item'),
                'unique_together': {('item', 'expire_date')},
            },
        ),
    ]
