# Generated by Django 3.0.5 on 2021-07-20 06:03

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='code', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
