# Generated by Django 3.0.5 on 2021-07-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210720_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
