# Generated by Django 3.0.4 on 2020-04-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200401_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Цена'),
        ),
    ]
