# Generated by Django 3.0.5 on 2021-07-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210720_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Название'),
        ),
    ]
