# Generated by Django 3.0.5 on 2020-04-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200402_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
    ]
