# Generated by Django 3.0.5 on 2021-07-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210720_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Остаток на складе'),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity_lots',
            field=models.CharField(default='', max_length=250, verbose_name='Остаток на складе: размеры остатков'),
        ),
    ]
