# Generated by Django 3.0.5 on 2021-07-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210727_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity_unit',
            field=models.CharField(choices=[('GRM', 'грамм'), ('KGM', 'килограмм'), ('LTR', 'литр'), ('MMT', 'миллиметр'), ('MTK', 'квадратный метр'), ('MTQ', 'кубический метр'), ('MTR', 'метр'), ('MGM', 'миллиграмм'), ('MLT', 'миллилитр'), ('MMQ', 'миллиметр кубический'), ('PCE', 'штук'), ('DMQ', 'дециметр кубический'), ('CMT', 'сантиметр'), ('NMP', 'упаковка'), ('NBB', 'бобина(бухта)')], default='PCE', max_length=3),
        ),
    ]
