# Generated by Django 3.0.5 on 2020-04-03 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_auto_20200402_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='shop.Item'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'item')},
        ),
    ]
