# Generated by Django 3.0.5 on 2021-07-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210728_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базоваяя цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specvalue',
            name='value',
            field=models.CharField(max_length=150, null=True, verbose_name='Значение характеристики'),
        ),
        migrations.AlterUniqueTogether(
            name='specvalue',
            unique_together={('spec_item', 'item')},
        ),
    ]
