# Generated by Django 3.0.5 on 2020-04-09 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_item_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specvalue',
            options={'verbose_name': 'Значение характеристики', 'verbose_name_plural': 'Значения характеристик'},
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, db_index=True, default='', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='specitem',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.SpecValue', verbose_name='Значение характеристики'),
        ),
    ]
