# Generated by Django 3.0.5 on 2020-04-29 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200428_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartitems',
            options={'verbose_name': 'Продукт из корзины', 'verbose_name_plural': 'Продукты находящиеся в корзинах'},
        ),
        migrations.RenameField(
            model_name='cartitems',
            old_name='price_with_discount',
            new_name='price_on_order_date',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='cart',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='shop.Order'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity_unit',
            field=models.CharField(choices=[('0', 'шт'), ('1', 'кг'), ('2', 'метр')], default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
