# Generated by Django 3.0.5 on 2021-07-01 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200401_0836'),
        ('shop', '0014_auto_20210701_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name': 'Заказанный товар', 'verbose_name_plural': 'Заказанные товары'},
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='account.Profile', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Заказан'), ('1', 'Оплачен'), ('2', 'В доставке'), ('3', 'Доставлен'), ('4', 'Выполнен')], default='1', max_length=1),
        ),
    ]
