# Generated by Django 3.0.5 on 2021-07-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210701_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Заказан'), ('1', 'Оплачен'), ('2', 'В доставке'), ('3', 'Доставлен'), ('4', 'Выполнен'), ('5', 'Анулирован')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='shop.Order'),
        ),
    ]
