# Generated by Django 3.0.5 on 2021-07-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210701_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
